default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  password: "#Because008"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: saas_db

test:
  <<: *default
  database: test_saas_db

production:
  <<: *default
  database: prod_saas_db
